language: node_js
node_js:
- '0.12'

env:
  global:
    secure: AeN77Oqn+P5POAzwccpEOnJkZ2GRDTdEmxV+yRgemB3bKpeqWw4AOuCupX8bjlohN4yAHQoCGuzUgtupEcUY//FxErq148PVA76eHQC9rW1oDxBoo5K/1ldZb0XT2bY7XDOmIbvj6bar0wQeTHDluu7wCXihBvYZnNSq1WAaWQ3Jj3zBfcIiwkawg+Qc9SP1mLKa6DsQ9vkBdzoYLsJGs3NkIiPJL7csRZYoU5fEMD7J5Hi2/5Yeuoaq0pkWaibL1AYrf+TgqDFmJcdnXVvgHsuODI3V2EUGGzbo2gV3JjKT0+xyjbWBABmF1gZmyqLFosugTgaoVH9DNv95EhqBNcOpgmpsnotSA6SE7zTzjAaxEn8HfooxFZh3280t3prQuTc2rCDum+aM8BYBeMc8cjhl37VzVD224rfUmMM8GqYOnjRMztPsTcRyXMMCg7BkHod9zH1L0dQrpOZL2wPZ3YSHdcsZ7dGwBLnywxKp56VnT34nnOuKtdgeMx9my9FEiNix+H3YO9Ka8bK+Moh5DYiwULwxV97eJ6BV6VGaMQXGetLptz49BDLtp02G2TTcCJ+BVjCoRXwdxeaG/Gvek6hcuykcGyeXM1bun9uAVRjiCWDdcf6CuVPyBA8XXhBOqFKEKE/0M+U5AOtpfhZo+UcAmYd1VaQ6eOwzBWlcfS0=

before_install:
- npm install -g grunt-cli

script:
- npm test

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && grunt autoDeploy
