language: node_js
node_js:
- '0.12'

before_install:
- npm install -g grunt-cli

script:
- npm test

deploy:
  provider: heroku
  api_key:
    secure: "YNJCKXZPbRvIEUGvgxN2QdHLguOslelkCp5hqjH3fGlyrD0f3x3/YMDCeRKyVjPdUPIw2W6JK/vPEsA/Yb68z6MB1WX1Vy2PK6nrLVVnVr+Sn41TheJ5t0cJfArwXcc1yF1zYEtmnEb4a8KLCabXCpryz8AA74Ce911urcPXyryxjxCTopLYdjcQ/JKrnhnc/LYFllofwCZelQROcgjCkLNLn3VtlI6gVyginXTaQEib2Wmr8p8YGznbjohd5MVXRxf4I4GNTBMFZ7OOeMRIhuNWTxcofQ8gzztnFjfxM0xNaY/Uqq4yTHdUGtX6a1TAg9EpjQCPIqovaozhZdpFjaoKM2ygBajjtvX7AO29QD+BHkSt/LzvbD+QI9mJYK9qD2A8MqVSevfMe1BIdCekoKsri+Iy78TeHJG5w9bFAiO7MPOuy15YfbT44qqvoF6ZJTYPWtLm5BGNb3p9+o27NlG72OOWsZAB++u6m697Q344Er/Np14PAz4O7zYduT5OVdiZGtdtyXcRkXb3hQKcPHoWf1lDwjhWbdG2oBRwRVcJ/xX28gYocH+QK+Tj58n3/jkqAS57as6JxpR6vyKtmEX+x6d2J0Db/E34m0gGmmxp1xyNfB8QAACPLw98e7nh5yoXOMetxnuOAXYWNxVL6PUMPCZcCMYiAe2Ft++Vt8U="
  app:
    master: travis-web-data-connector
